apiVersion: v1alpha1
kind: Setting
metadata:
  name: theme-mtxst-setting
spec:
  forms:
    - group: layout
      label: 布局
      formSchema:
        - $formkit: repeater
          name: swiper_image
          label: 首页轮播图片
          value: []
          children:
            - $formkit: attachment
              name: img
              label: 轮播图片

        - $formkit: repeater
          name: swiper_video
          label: 首页轮播视频
          value: []
          children:
            - $formkit: attachment
              name: image
              label: 视频缩略图
            - $formkit: attachment
              name: video
              label: 视频

    - group: sidebar
      label: 侧边栏
      formSchema:
        - $formkit: group
          name: profile
          value:
            logo:
          children:
            - $formkit: attachment
              name: logo
              label: 站点资料 Logo

    - group: beian
      label: 备案设置
      formSchema:
        - $formkit: text
          name: icp_text
          label: ICP备案号
        - $formkit: text
          name: icp_link
          label: ICP备案跳转链接
          value: https://beian.miit.gov.cn/

        - $formkit: text
          name: gongan_text
          label: 公安联网备案号
        - $formkit: text
          name: gongan_link
          label: 公安联网备案跳转链接
          value: https://beian.mps.gov.cn/#/query/webSearch

    
    - group: company
      label: 公司信息
      formSchema:
        - $formkit: text
          name: address
          label: 公司地址
          value: 湖南省长沙市岳麓区学士街道玉莲路32号联东优谷工业园一号地9栋202号房
        
        - $formkit: text
          name: tel
          label: 公司联系电话
          value: 400-021-0988，0731-89576909

        - $formkit: text
          name: name
          label: 公司名称
          value: Copyright © 2023 长沙市卓成医疗器械有限公司。
        
        - $formkit: text
          name: url
          label: 公司网站地址
          value: https://www.cszcyl.cn

        - $formkit: attachment
          name: logo
          label: 公司Logo
    
    - group: notice
      label: 公告产品图片设置
      formSchema:
        - $formkit: repeater
          name: notice_jy_img
          label: 煎药机图片
          value: []
          children:
            - $formkit: attachment
              name: img
              label: 图片

        - $formkit: repeater
          name: notice_zw_img
          label: 制丸机图片
          value: []
          children:
            - $formkit: attachment
              name: img
              label: 图片
        
        - $formkit: repeater
          name: notice_fs_img
          label: 粉碎机图片
          value: []
          children:
            - $formkit: attachment
              name: img
              label: 图片


